name: Build Wheels (Trusted Publisher)

on:
  workflow_dispatch:
  push:
    tags:
      - "utils-v*"

permissions:
  id-token: write
  contents: read

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify tag matches pyproject version
        if: startsWith(github.ref, 'refs/tags/utils-v')
        run: |
          python - << 'PY'
          import os, tomllib
          tag = os.environ['GITHUB_REF_NAME'].split('utils-v', 1)[1]
          with open('pyproject.toml','rb') as f:
              version = tomllib.load(f)['project']['version']
          assert version == tag, f"version mismatch: tag={tag} pyproject={version}"
          print('version OK:', version)
          PY

      - name: Ensure cache dirs exist
        run: mkdir -p .ccache .pip-cache

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/src/**', '**/meson.build') }}
          restore-keys: ccache-${{ runner.os }}-

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: .pip-cache
          key: pip-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: pip-${{ runner.os }}-

      - run: brew install ccache
      - run: python -m pip install cibuildwheel==3.1.3

      - name: Build wheels (macOS)
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-*"
          CIBW_SKIP: "cp38-* cp39-* cp310-* cp312-* cp313-* cp314-*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT_MACOS: >-
            CC='ccache clang' CXX='ccache clang++'
            CCACHE_DIR=${{ github.workspace }}/.ccache
            CCACHE_MAXSIZE=1G
            PIP_CACHE_DIR=${{ github.workspace }}/.pip-cache
          CIBW_BEFORE_BUILD: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install meson meson-python ninja
          CIBW_TEST_COMMAND: python -c "import retracesoftware_utils; print('ok')"

      - name: ccache stats (macOS)
        run: ccache -s || true

      - name: Upload wheels (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: utils-macos-wheels
          path: wheelhouse/*.whl
          retention-days: 7

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify tag matches pyproject version
        if: startsWith(github.ref, 'refs/tags/utils-v')
        run: |
          python - << 'PY'
          import os, tomllib
          tag = os.environ['GITHUB_REF_NAME'].split('utils-v', 1)[1]
          with open('pyproject.toml','rb') as f:
            version = tomllib.load(f)['project']['version']
          assert version == tag, f"version mismatch: tag={tag} pyproject={version}"
          print('version OK:', version)
          PY

      - name: Enable QEMU for cross-arch builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Ensure cache dirs exist
        run: mkdir -p .ccache .pip-cache

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/src/**', '**/meson.build') }}
          restore-keys: ccache-${{ runner.os }}-

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: .pip-cache
          key: pip-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: pip-${{ runner.os }}-

      - run: sudo apt-get update && sudo apt-get install -y ccache
      - run: python -m pip install cibuildwheel==3.1.3

      - name: Build wheels (Linux)
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-*"
          CIBW_SKIP: "cp38-* cp39-* cp310-* cp312-* cp313-* cp314-*"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ENVIRONMENT_LINUX: >-
            CC='ccache gcc' CXX='ccache g++'
            CCACHE_DIR=/project/.ccache
            CCACHE_MAXSIZE=1G
            PIP_CACHE_DIR=/project/.pip-cache
          CIBW_BEFORE_ALL_LINUX: >-
            (yum -y install ccache || dnf -y install ccache || microdnf -y install ccache || true)
          CIBW_BEFORE_BUILD: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install meson meson-python ninja
          CIBW_TEST_COMMAND: python -c "import retracesoftware_utils; print('ok')"

      - name: ccache stats (Linux host)
        run: ccache -s || true

      - name: Upload wheels (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: utils-linux-wheels
          path: wheelhouse/*.whl
          retention-days: 7

  publish_pypi:
    if: startsWith(github.ref, 'refs/tags/utils-v')
    needs: [build_macos, build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: utils-macos-wheels
          path: upload

      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          name: utils-linux-wheels
          path: upload

      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: upload
          skip-existing: true
